# Generated by Django 2.2.3 on 2020-03-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItem_dj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('store_id', models.IntegerField()),
                ('position', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('item_id', models.IntegerField()),
                ('hole_num', models.IntegerField()),
                ('hole_1', models.CharField(max_length=100)),
                ('hole_2', models.CharField(max_length=100)),
                ('hole_3', models.CharField(max_length=100)),
                ('hole_4', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('price', models.IntegerField()),
                ('num', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
