# Generated by Django 2.2.3 on 2020-04-05 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseItem_dj',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('image_link', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=30)),
                ('equipment_location', models.CharField(max_length=30)),
                ('buy_price', models.IntegerField(null=True)),
                ('sell_price', models.IntegerField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('atk', models.IntegerField(null=True)),
                ('matk', models.IntegerField(null=True)),
                ('defense', models.IntegerField(null=True)),
                ('attack_distance', models.IntegerField(null=True)),
                ('hole_num', models.IntegerField()),
                ('refinable', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapyItem',
            fields=[
                ('start_time', models.DateTimeField(primary_key=True, serialize=False)),
                ('end_time', models.DateTimeField(null=True)),
                ('item_num', models.IntegerField(null=True)),
                ('time_cost', models.FloatField(null=True)),
                ('fail_num', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='StoreItem_dj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('store_id', models.IntegerField()),
                ('position', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('hole_num', models.IntegerField()),
                ('hole_1', models.CharField(max_length=100)),
                ('hole_2', models.CharField(max_length=100)),
                ('hole_3', models.CharField(max_length=100)),
                ('hole_4', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('price', models.IntegerField()),
                ('num', models.IntegerField()),
                ('base_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.BaseItem_dj')),
                ('scrapy_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.ScrapyItem')),
            ],
        ),
        migrations.CreateModel(
            name='WantedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_price', models.IntegerField()),
                ('level', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now=True)),
                ('hole_string', models.CharField(blank=True, max_length=400)),
                ('highest_price', models.IntegerField(blank=True, null=True)),
                ('lowest_price', models.IntegerField(blank=True, null=True)),
                ('avg_price', models.FloatField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
                ('base_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.BaseItem_dj')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store_items', models.ManyToManyField(to='crawler.StoreItem_dj')),
            ],
        ),
    ]
