# Generated by Django 2.2.3 on 2020-03-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseItem_dj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('image_link', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=30)),
                ('equipment_location', models.CharField(max_length=30)),
                ('buy_price', models.IntegerField()),
                ('sell_price', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('atk', models.IntegerField()),
                ('matk', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('attack_distance', models.IntegerField()),
                ('hole_num', models.IntegerField()),
                ('refinable', models.BooleanField()),
            ],
        ),
    ]
