# Generated by Django 2.2.3 on 2020-03-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_baseitem_dj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseitem_dj',
            name='id',
        ),
        migrations.AlterField(
            model_name='baseitem_dj',
            name='item_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
