# Generated by Django 2.2.3 on 2020-03-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_auto_20200327_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('item_num', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='baseitem_dj',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
