# Generated by Django 2.2.3 on 2020-03-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0007_auto_20200327_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapyitem',
            name='id',
        ),
        migrations.AlterField(
            model_name='scrapyitem',
            name='start_time',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
